run:
  deadline: 10m10s
  modules-download-mode: vendor

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - nakedret
    - misspell
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - vet
    - vetshadow
    - whitespace

linters-settings:
  stylecheck:
    ignore: ST1003
  misspell:
    locale: uk