run:
  deadline: 10m10s
  modules-download-mode: vendor
  go: 1.22 # 1.18 disabled some linters as they don't support generics yet, as such lock to 1.17 until they do

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - decorder
    - durationcheck
    - errchkjson
    - errname
    - errcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - noctx
    - makezero
    - misspell
    #- paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - revive
    - typecheck
    - unused
    - unconvert
    - unparam
    - govet
    - wastedassign
    - whitespace
    # - wsl #linter configuration is still quite not flexible enough for my liking, leaving disabled for now

linters-settings:
  errcheck:
    exclude-functions: io:Close
  misspell:
    locale: uk
  nlreturn:
    block-size: 4
  wsl:
    allow-assign-and-anything: true
    allow-separated-leading-comment: true
    allow-trailing-comment: true
    allow-cuddle-declarations: true
    allow-multiline-assign: true
    force-case-trailing-whitespace: 1
    enforce-err-cuddling: true

