run:
  deadline: 10m10s
  modules-download-mode: vendor
  go: 1.18

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - deadcode
    - durationcheck
    - errname
    - errcheck
    - exhaustive
    - exportloopref
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - gosec
    #- godot
    - ineffassign
    - ifshort
    - nakedret
    - nilnil
    - nolintlint
    - makezero
    - misspell
    - staticcheck
    - structcheck
    #- stylecheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - varcheck
    - vet
    - vetshadow
    - whitespace
  #- wsl

linters-settings:
  stylecheck:
    ignore: ST1003
  misspell:
    locale: uk