// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/generate/servicepackage/main.go; DO NOT EDIT.

package rekognition

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/rekognition"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	inttypes "github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*inttypes.ServicePackageFrameworkDataSource {
	return []*inttypes.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*inttypes.ServicePackageFrameworkResource {
	return []*inttypes.ServicePackageFrameworkResource{
		{
			Factory:  newCollectionResource,
			TypeName: "aws_rekognition_collection",
			Name:     "Collection",
			Tags: inttypes.ServicePackageResourceTags{
				IdentifierAttribute: names.AttrARN,
			},
		},
		{
			Factory:  newProjectResource,
			TypeName: "aws_rekognition_project",
			Name:     "Project",
		},
		{
			Factory:  newStreamProcessorResource,
			TypeName: "aws_rekognition_stream_processor",
			Name:     "Stream Processor",
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.Rekognition
}

// NewClient returns a new AWS SDK for Go v2 client for this service package's AWS API.
func (p *servicePackage) NewClient(ctx context.Context, config map[string]any) (*rekognition.Client, error) {
	cfg := *(config["aws_sdkv2_config"].(*aws.Config))

	return rekognition.NewFromConfig(cfg,
		func(o *rekognition.Options) {
			if endpoint := config[names.AttrEndpoint].(string); endpoint != "" {
				o.BaseEndpoint = aws.String(endpoint)
			}
		},
	), nil
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
