// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/generate/tags/main.go; DO NOT EDIT.

package rekognition

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/rekognition"
	tftags "github.com/hashicorp/terraform-provider-aws/internal/tags"
)

// listTags lists rekognition service tags.
// The identifier is typically the Amazon Resource Name (ARN), although
// it may also be a different identifier depending on the service.
func listTags(ctx context.Context, conn *rekognition.Client, identifier string) (tftags.KeyValueTags, error) {
	input := &rekognition.ListTagsForResourceInput{
		ResourceArn: aws.String(identifier),
	}

	output, err := conn.ListTagsForResource(ctx, input)
	if err != nil {
		return tftags.New(ctx, nil), err
	}

	return tftags.New(ctx, output.Tags), nil
}
